name: Gradle Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      - name: Start Xvfb
        run: Xvfb :99 & export DISPLAY=:99

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Run Gradle tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          Xvfb :99 & export DISPLAY=:99
          ./gradlew test

      - name: Upload Test Reports
        if: always() # always run even if the previous step failed or was cancelled
        uses: actions/upload-artifact@v4
        with:
          name: Test-Reports
          path: '**/target/*-reports/*'

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always() # always run even if the previous step failed or was cancelled
        with:
          report_paths: '**/target/*-reports/TEST-*.xml'
          annotate_only: true
